import { cp, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, test } from 'vitest';

import { codexAdapter } from '../src/adapters/codex.js';
import { KernelFileExistsError } from '../src/core/fs.js';
import { compileAdapter, renderGeneratedAdapterFile } from '../src/core/adapter-compiler.js';
import { GENERATED_FILE_HEADER } from '../src/core/manual-sections.js';

const tempDirs: string[] = [];

async function copyFixture(name: string): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), `kernel-compile-${name}-`));
  tempDirs.push(dir);
  await cp(join(process.cwd(), 'tests', 'fixtures', name), dir, { recursive: true });
  return dir;
}

async function readText(path: string): Promise<string> {
  return readFile(path, 'utf8');
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((dir) => rm(dir, { recursive: true, force: true })));
});

describe('codexAdapter', () => {
  test('renders minimal Codex outputs from canonical Kernel config', async () => {
    const rootDir = await copyFixture('compile-codex-basic');

    const result = await compileAdapter(rootDir, codexAdapter, { dryRun: true });

    expect(result.adapterName).toBe('codex');
    expect(result.files.map((file) => file.relativePath)).toEqual([
      'AGENTS.md',
      '.agents/skills/kernel-core/SKILL.md'
    ]);
    expect(result.files.map((file) => file.content)).toMatchInlineSnapshot(`
      [
        "<!-- Generated by Kernel. Edit canonical source under .agent/ instead. -->

      # AGENTS.md

      This repository uses **Kernel** for repo-local task contracts, verification evidence, and agent handoffs.

      Project: Codex Fixture

      ## Prime directive

      No contract, no implementation. No evidence, no completion. No handoff, no continuity.

      ## Canonical source

      - Kernel config: \`.agent/kernel.yaml\`
      - Current task: \`.agent/state/current-task.md\`
      - Task contracts: \`.agent/contracts/\`
      - Evidence ledgers: \`.agent/evidence/\`
      - Handoff packets: \`.agent/handoffs/\`
      - Repository maps: \`.agent/maps/\`

      ## Codex workflow

      1. Read \`AGENTS.md\` and \`.agent/kernel.yaml\` before non-trivial implementation.
      2. Create or update \`.agent/state/current-task.md\` before implementation.
      3. Prefer minimal, testable changes.
      4. Record verification evidence before claiming completion.
      5. Create a handoff packet when work is incomplete or likely to move to another ADE.

      <!-- kernel:manual:start -->

      <!-- kernel:manual:end -->
      ",
        "<!-- Generated by Kernel. Edit canonical source under .agent/ instead. -->

      ---
      name: kernel-core
      description: Use before and after non-trivial coding-agent tasks in repositories using Kernel. Creates or updates task contracts, identifies context and risk, requires evidence before completion, and creates handoff packets when needed. Do not use for trivial one-line edits unless the touched area is high-risk.
      ---

      # kernel-core

      ## Purpose

      Use this Codex skill to follow Kernel's repo-local operating protocol for Codex Fixture.

      ## Procedure

      1. Read \`AGENTS.md\` and \`.agent/kernel.yaml\`.
      2. Read or create \`.agent/state/current-task.md\`.
      3. Define goal, non-goals, assumptions, risk zones, verification, and done criteria.
      4. Make minimal, testable changes.
      5. Record evidence in \`.agent/evidence/\` before claiming completion.
      6. Create a handoff packet in \`.agent/handoffs/\` when work is incomplete or long-running.

      ## Output

      Durable Kernel artifacts under \`.agent/\`.

      <!-- kernel:manual:start -->

      <!-- kernel:manual:end -->
      ",
      ]
    `);
  });
});

describe('renderGeneratedAdapterFile', () => {
  test('adds generated header and preserves manual sections', () => {
    const existing = [
      GENERATED_FILE_HEADER,
      '',
      '# Old',
      '<!-- kernel:manual:start -->',
      'Keep manual content.',
      '<!-- kernel:manual:end -->',
      ''
    ].join('\n');

    const next = ['# New', '<!-- kernel:manual:start -->', '', '<!-- kernel:manual:end -->', ''].join('\n');

    expect(renderGeneratedAdapterFile(next, existing)).toContain('Keep manual content.');
    expect(renderGeneratedAdapterFile(next, existing)).toMatch(/^<!-- Generated by Kernel/);
  });
});

describe('compileAdapter', () => {
  test('supports dry-run without writing Codex outputs', async () => {
    const rootDir = await copyFixture('compile-codex-basic');

    const result = await compileAdapter(rootDir, codexAdapter, { dryRun: true });

    expect(result.files.map((file) => file.action)).toEqual(['would-create', 'would-create']);
    await expect(readText(join(rootDir, 'AGENTS.md'))).rejects.toThrow();
    await expect(readText(join(rootDir, '.agents', 'skills', 'kernel-core', 'SKILL.md'))).rejects.toThrow();
  });

  test('refuses existing Codex outputs by default before writing files', async () => {
    const rootDir = await copyFixture('compile-codex-existing');
    const originalAgents = await readText(join(rootDir, 'AGENTS.md'));
    const originalSkill = await readText(join(rootDir, '.agents', 'skills', 'kernel-core', 'SKILL.md'));

    await expect(compileAdapter(rootDir, codexAdapter)).rejects.toBeInstanceOf(KernelFileExistsError);

    await expect(readText(join(rootDir, 'AGENTS.md'))).resolves.toBe(originalAgents);
    await expect(readText(join(rootDir, '.agents', 'skills', 'kernel-core', 'SKILL.md'))).resolves.toBe(
      originalSkill
    );
  });

  test('supports force overwrite and preserves manual sections', async () => {
    const rootDir = await copyFixture('compile-codex-existing');

    const result = await compileAdapter(rootDir, codexAdapter, { force: true });

    expect(result.files.map((file) => file.action)).toEqual(['updated', 'updated']);
    const agents = await readText(join(rootDir, 'AGENTS.md'));
    const skill = await readText(join(rootDir, '.agents', 'skills', 'kernel-core', 'SKILL.md'));
    expect(agents).toContain('Project: Existing Codex Fixture');
    expect(agents).toContain('Keep this AGENTS manual section.');
    expect(skill).toContain('Use this Codex skill to follow Kernel');
    expect(skill).toContain('Keep this skill manual section.');
  });
});
