import { describe, expect, test } from 'vitest';

import { MANUAL_END, MANUAL_START, preserveManualSections } from '../src/core/manual-sections.js';

describe('preserveManualSections', () => {
  test('preserves manual content during regeneration', () => {
    const existingContent = [
      '<!-- Generated by Kernel. Edit canonical source under .agent/ instead. -->',
      '',
      '# Existing',
      MANUAL_START,
      'Keep this user-authored note.',
      MANUAL_END,
      ''
    ].join('\n');

    const nextContent = ['# Regenerated', MANUAL_START, '', MANUAL_END, ''].join('\n');

    expect(preserveManualSections(nextContent, existingContent)).toBe(
      ['# Regenerated', MANUAL_START, 'Keep this user-authored note.', MANUAL_END, ''].join('\n')
    );
  });

  test('returns new content unchanged when markers are missing', () => {
    expect(preserveManualSections('new\n', 'old\n')).toBe('new\n');
  });
});
