import { cp, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, test } from 'vitest';

import { KernelFileExistsError } from '../src/core/fs.js';
import { compileAdapters } from '../src/core/adapter-compiler.js';
import { getAdapter, getAdaptersForTarget } from '../src/adapters/index.js';
import { GENERATED_FILE_HEADER } from '../src/core/manual-sections.js';

const tempDirs: string[] = [];

async function copyFixture(name: string): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), `kernel-priority-adapters-${name}-`));
  tempDirs.push(dir);
  await cp(join(process.cwd(), 'tests', 'fixtures', name), dir, { recursive: true });
  return dir;
}

async function readText(path: string): Promise<string> {
  return readFile(path, 'utf8');
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((dir) => rm(dir, { recursive: true, force: true })));
});

describe('priority adapter registry', () => {
  test('resolves supported adapter targets and compile-all order', () => {
    expect(getAdapter('claude').name).toBe('claude');
    expect(getAdapter('cursor').name).toBe('cursor');
    expect(getAdapter('kiro').name).toBe('kiro');
    expect(getAdapter('github-copilot').name).toBe('github-copilot');
    expect(getAdaptersForTarget('all').map((adapter) => adapter.name)).toEqual([
      'codex',
      'claude',
      'cursor',
      'kiro',
      'github-copilot'
    ]);
  });

  test('throws for unsupported adapter targets', () => {
    expect(() => getAdaptersForTarget('gemini')).toThrow('Unsupported adapter target: gemini');
  });
});

describe('priority adapter rendering', () => {
  test('renders expected output paths for each new priority adapter', async () => {
    const rootDir = await copyFixture('compile-all-basic');

    const claude = await compileAdapters(rootDir, [getAdapter('claude')], { dryRun: true });
    const cursor = await compileAdapters(rootDir, [getAdapter('cursor')], { dryRun: true });
    const kiro = await compileAdapters(rootDir, [getAdapter('kiro')], { dryRun: true });
    const github = await compileAdapters(rootDir, [getAdapter('github-copilot')], { dryRun: true });

    expect(claude.files.map((file) => file.relativePath)).toEqual([
      'CLAUDE.md',
      '.claude/skills/kernel-core/SKILL.md',
      '.claude/skills/kernel-review/SKILL.md',
      '.claude/skills/kernel-debug/SKILL.md',
      '.claude/skills/kernel-handoff/SKILL.md'
    ]);
    expect(cursor.files.map((file) => file.relativePath)).toEqual([
      '.cursor/rules/kernel-core.mdc',
      '.cursor/rules/kernel-quality.mdc',
      '.cursor/rules/kernel-security.mdc'
    ]);
    expect(kiro.files.map((file) => file.relativePath)).toEqual([
      '.kiro/steering/kernel.md',
      '.kiro/steering/verification.md',
      '.kiro/hooks/kernel-evidence.json',
      '.kiro/specs/kernel/requirements.md'
    ]);
    expect(github.files.map((file) => file.relativePath)).toEqual([
      '.github/copilot-instructions.md',
      '.github/instructions/testing.instructions.md',
      '.github/instructions/review.instructions.md',
      '.github/skills/kernel-core/SKILL.md'
    ]);
  });

  test('snapshot-tests representative generated content', async () => {
    const rootDir = await copyFixture('compile-all-basic');

    const result = await compileAdapters(
      rootDir,
      [getAdapter('claude'), getAdapter('cursor'), getAdapter('kiro'), getAdapter('github-copilot')],
      { dryRun: true }
    );

    expect(
      result.files
        .filter((file) =>
          ['CLAUDE.md', '.cursor/rules/kernel-core.mdc', '.kiro/hooks/kernel-evidence.json', '.github/copilot-instructions.md'].includes(
            file.relativePath
          )
        )
        .map((file) => ({ path: file.relativePath, content: file.content }))
    ).toMatchInlineSnapshot(`
      [
        {
          "content": "<!-- Generated by Kernel. Edit canonical source under .agent/ instead. -->

      # CLAUDE.md

      This repository uses **Kernel** for repo-local task contracts, verification evidence, and handoffs.

      Project: Multi Adapter Fixture

      ## Prime directive

      No contract, no implementation. No evidence, no completion. No handoff, no continuity.

      ## Canonical source

      - Kernel config: \`.agent/kernel.yaml\`
      - Current task: \`.agent/state/current-task.md\`
      - Task contracts: \`.agent/contracts/\`
      - Evidence ledgers: \`.agent/evidence/\`
      - Handoff packets: \`.agent/handoffs/\`
      - Repository maps: \`.agent/maps/\`

      <!-- kernel:manual:start -->

      <!-- kernel:manual:end -->
      ",
          "path": "CLAUDE.md",
        },
        {
          "content": "<!-- Generated by Kernel. Edit canonical source under .agent/ instead. -->

      # Kernel Core

      Always use Kernel's canonical source under \`.agent/\` before non-trivial changes in Multi Adapter Fixture.

      - Read \`.agent/kernel.yaml\`.
      - Read or create \`.agent/state/current-task.md\`.
      - Record evidence under \`.agent/evidence/\` before claiming completion.

      <!-- kernel:manual:start -->

      <!-- kernel:manual:end -->
      ",
          "path": ".cursor/rules/kernel-core.mdc",
        },
        {
          "content": "<!-- Generated by Kernel. Edit canonical source under .agent/ instead. -->

      {
        "name": "kernel-evidence",
        "description": "Require Kernel evidence before completion claims.",
        "project": "Multi Adapter Fixture",
        "canonicalEvidencePath": ".agent/evidence/",
        "canonicalTaskPath": ".agent/state/current-task.md"
      }
      ",
          "path": ".kiro/hooks/kernel-evidence.json",
        },
        {
          "content": "<!-- Generated by Kernel. Edit canonical source under .agent/ instead. -->

      # GitHub Copilot Instructions

      This repository uses **Kernel** for repo-local agent quality artifacts.

      Project: Multi Adapter Fixture

      Before non-trivial changes, inspect \`.agent/kernel.yaml\` and \`.agent/state/current-task.md\`.
      Record verification in \`.agent/evidence/\` before claiming completion.

      <!-- kernel:manual:start -->

      <!-- kernel:manual:end -->
      ",
          "path": ".github/copilot-instructions.md",
        },
      ]
    `);
  });
});

describe('compileAdapters', () => {
  test('supports compile all in deterministic output order', async () => {
    const rootDir = await copyFixture('compile-all-basic');

    const result = await compileAdapters(rootDir, getAdaptersForTarget('all'), { dryRun: true });

    expect(result.adapterNames).toEqual(['codex', 'claude', 'cursor', 'kiro', 'github-copilot']);
    expect(result.files.map((file) => file.relativePath)).toEqual([
      'AGENTS.md',
      '.agents/skills/kernel-core/SKILL.md',
      'CLAUDE.md',
      '.claude/skills/kernel-core/SKILL.md',
      '.claude/skills/kernel-review/SKILL.md',
      '.claude/skills/kernel-debug/SKILL.md',
      '.claude/skills/kernel-handoff/SKILL.md',
      '.cursor/rules/kernel-core.mdc',
      '.cursor/rules/kernel-quality.mdc',
      '.cursor/rules/kernel-security.mdc',
      '.kiro/steering/kernel.md',
      '.kiro/steering/verification.md',
      '.kiro/hooks/kernel-evidence.json',
      '.kiro/specs/kernel/requirements.md',
      '.github/copilot-instructions.md',
      '.github/instructions/testing.instructions.md',
      '.github/instructions/review.instructions.md',
      '.github/skills/kernel-core/SKILL.md'
    ]);
    expect(result.files.every((file) => file.content.startsWith(GENERATED_FILE_HEADER))).toBe(true);
  });

  test('refuses existing outputs before writing any compile-all files by default', async () => {
    const rootDir = await copyFixture('compile-all-existing');
    const originalClaude = await readText(join(rootDir, 'CLAUDE.md'));

    await expect(compileAdapters(rootDir, getAdaptersForTarget('all'))).rejects.toBeInstanceOf(KernelFileExistsError);

    await expect(readText(join(rootDir, 'CLAUDE.md'))).resolves.toBe(originalClaude);
    await expect(readText(join(rootDir, 'AGENTS.md'))).rejects.toThrow();
  });

  test('supports force overwrite and preserves manual sections', async () => {
    const rootDir = await copyFixture('compile-all-existing');

    const result = await compileAdapters(rootDir, [getAdapter('claude')], { force: true });

    expect(result.files.map((file) => file.action)).toEqual(['updated', 'created', 'created', 'created', 'created']);
    const claude = await readText(join(rootDir, 'CLAUDE.md'));
    expect(claude).toContain('Project: Existing Multi Adapter Fixture');
    expect(claude).toContain('Keep this Claude manual section.');
  });
});
