import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import type { Command } from 'commander';
import { afterEach, describe, expect, test, vi } from 'vitest';

import { createKernelProgram } from '../src/cli/index.js';

const repoRoot = process.cwd();
const tempDirs: string[] = [];

afterEach(async () => {
  vi.restoreAllMocks();
  await Promise.all(tempDirs.splice(0).map((dir) => rm(dir, { recursive: true, force: true })));
});

describe('Kernel release-readiness workflow', () => {
  test('runs the core CLI workflow in a temporary repository', async () => {
    const rootDir = await createReleaseFixture();

    const init = await runCli(['init'], rootDir);
    expect(init).toMatchObject({ exitCode: 0, stderr: '' });
    expect(init.stdout).toContain('created: .agent');
    await expect(readFile(join(rootDir, '.agent', 'kernel.yaml'), 'utf8')).resolves.toContain('version: 1');
    await expect(readFile(join(rootDir, 'AGENTS.md'), 'utf8')).resolves.toContain('Generated by Kernel');

    const skillGenerate = await runCli(
      ['skill', 'generate', '--docs-vault', 'public_docs_fixture', '--set', 'lint-ready', '--json'],
      rootDir
    );
    const skillGenerateJson = JSON.parse(skillGenerate.stdout) as {
      schemaVersion: number;
      generationSet: string;
      dryRun: boolean;
      skills: string[];
      skipped: unknown[];
    };
    expect(skillGenerate).toMatchObject({ exitCode: 0, stderr: '' });
    expect(skillGenerateJson.schemaVersion).toBe(1);
    expect(skillGenerateJson.generationSet).toBe('lint-ready');
    expect(skillGenerateJson.dryRun).toBe(false);
    expect(skillGenerateJson.skills).toContain('kernel-core');
    expect(skillGenerateJson.skipped).toHaveLength(2);

    await writeKernelCoreEvalFixture(rootDir);

    const map = await runCli(['map', '--force'], rootDir);
    expect(map).toMatchObject({ exitCode: 0, stderr: '' });
    for (const fileName of ['repo.json', 'commands.json', 'tests.json', 'risk.json']) {
      await expect(readFile(join(rootDir, '.agent', 'maps', fileName), 'utf8')).resolves.toContain('{');
    }

    const compile = await runCli(['compile', 'all', '--force'], rootDir);
    expect(compile).toMatchObject({ exitCode: 0, stderr: '' });
    for (const relativePath of [
      'AGENTS.md',
      'CLAUDE.md',
      '.agents/skills/kernel-core/SKILL.md',
      '.claude/skills/kernel-core/SKILL.md',
      '.cursor/rules/kernel-core.mdc',
      '.kiro/steering/kernel.md',
      '.github/copilot-instructions.md'
    ]) {
      await expect(readFile(join(rootDir, relativePath), 'utf8')).resolves.toContain('Generated by Kernel');
    }

    const validation = await runJsonCli<{
      schemaVersion: number;
      status: string;
      errorCount: number;
      warningCount: number;
      issues: unknown[];
    }>(['validate', '--json'], rootDir);
    expect(validation.exitCode).toBe(0);
    expect(validation.parsed).toMatchObject({
      schemaVersion: 1,
      status: 'pass',
      errorCount: 0,
      warningCount: 0,
      issues: []
    });

    const skillLint = await runJsonCli<{
      schemaVersion: number;
      status: string;
      skillCount: number;
      fixtureCount: number;
      warningCount: number;
    }>(['skill', 'lint', '--json'], rootDir);
    expect(skillLint.exitCode).toBe(0);
    expect(skillLint.parsed).toMatchObject({
      schemaVersion: 1,
      status: 'pass',
      skillCount: 7,
      fixtureCount: 1,
      warningCount: 0
    });

    const evalResult = await runJsonCli<{
      schemaVersion: number;
      status: string;
      runnerId: string;
      fixtureCount: number;
      passCount: number;
      skipCount: number;
    }>(['eval', '--json'], rootDir);
    expect(evalResult.exitCode).toBe(0);
    expect(evalResult.parsed).toMatchObject({
      schemaVersion: 1,
      status: 'pass',
      runnerId: 'static',
      fixtureCount: 1,
      passCount: 1,
      skipCount: 0
    });

    const schemaVersions = await runJsonCli<{ schemaVersion: number; versions: string[] }>(
      ['schema', 'versions', '--json'],
      rootDir
    );
    expect(schemaVersions.parsed).toEqual({
      schemaVersion: 1,
      versions: ['v1']
    });

    const schemaList = await runJsonCli<{ schemas: Array<{ name: string }> }>(['schema', 'list', '--json'], rootDir);
    expect(schemaList.parsed.schemas.map((schema) => schema.name)).toEqual([
      'error-envelope',
      'schema-list-result',
      'schema-path-result',
      'schema-show-result',
      'schema-versions-result',
      'skill-eval-result',
      'skill-generate-result',
      'skill-lint-result',
      'validation-result'
    ]);

    const schemaPath = await runJsonCli<{ schema: { name: string }; path: string }>(
      ['schema', 'path', 'skill-eval-result', '--json'],
      rootDir
    );
    expect(schemaPath.parsed.schema.name).toBe('skill-eval-result');
    expect(schemaPath.parsed.path).toContain(join('schemas', 'json', 'v1', 'skill-eval-result.schema.json'));

    const schemaShow = await runJsonCli<{ schema: { name: string }; content: { title: string } }>(
      ['schema', 'show', 'skill-eval-result', '--json'],
      rootDir
    );
    expect(schemaShow.parsed.schema.name).toBe('skill-eval-result');
    expect(schemaShow.parsed.content.title).toBe('Kernel Skill Eval Result v1');
  });

  test('keeps package metadata ready for built CLI and schema distribution', async () => {
    const packageJson = JSON.parse(await readFile(join(repoRoot, 'package.json'), 'utf8')) as {
      name?: string;
      license?: string;
      private?: boolean;
      bin?: Record<string, string>;
      files?: string[];
      scripts?: Record<string, string>;
    };

    expect(packageJson.name).toBe('@mattbaconz/kernel');
    expect(packageJson.license).toBe('Apache-2.0');
    expect(packageJson.private).toBe(true);
    expect(packageJson.bin).toEqual({
      kernel: './dist/cli/index.js'
    });
    expect(packageJson.files).toEqual(expect.arrayContaining(['dist', 'schemas']));
    expect(packageJson.scripts).toEqual(
      expect.objectContaining({
        build: 'tsc -p tsconfig.build.json',
        test: 'vitest run',
        typecheck: 'tsc --noEmit -p tsconfig.json',
        lint: 'eslint .',
        'verify:packed': 'node scripts/verify-packed-cli.mjs'
      })
    );
    await expect(readFile(join(repoRoot, 'scripts', 'verify-packed-cli.mjs'), 'utf8')).resolves.toContain(
      'verifyPackedCli'
    );
    await expect(readFile(join(repoRoot, 'LICENSE'), 'utf8')).resolves.toContain('Copyright 2026 mattbaconz');
  });
});

async function createReleaseFixture(): Promise<string> {
  const rootDir = await mkdtemp(join(tmpdir(), 'kernel-release-readiness-'));
  tempDirs.push(rootDir);
  await mkdir(join(rootDir, 'src'), { recursive: true });
  await mkdir(join(rootDir, 'tests'), { recursive: true });
  await writeFile(
    join(rootDir, 'package.json'),
    `${JSON.stringify(
      {
        name: 'release-readiness-fixture',
        version: '0.0.0',
        scripts: {
          test: 'vitest run',
          build: 'tsc -p tsconfig.json'
        },
        dependencies: {}
      },
      null,
      2
    )}\n`,
    'utf8'
  );
  await writeFile(join(rootDir, 'src', 'index.ts'), 'export const answer = 42;\n', 'utf8');
  await writeFile(join(rootDir, 'tests', 'index.test.ts'), 'import "../src/index";\n', 'utf8');
  await cp(
    join(repoRoot, 'tests', 'fixtures', 'skill-generate-basic', 'public_docs_fixture'),
    join(rootDir, 'public_docs_fixture'),
    { recursive: true }
  );
  return rootDir;
}

async function writeKernelCoreEvalFixture(rootDir: string): Promise<void> {
  const fixtureDir = join(rootDir, '.agent', 'evals', 'skills', 'kernel-core');
  await mkdir(fixtureDir, { recursive: true });
  await writeFile(
    join(fixtureDir, 'basic.yaml'),
    ['name: kernel core activation', 'prompt: Implement a non-trivial feature.', 'expected:', '  activates: true', '  skills:', '    - kernel-core', ''].join('\n'),
    'utf8'
  );
}

async function runJsonCli<T>(args: string[], cwd: string): Promise<CliResult & { parsed: T }> {
  const result = await runCli(args, cwd);
  return {
    ...result,
    parsed: JSON.parse(result.stdout) as T
  };
}

interface CliResult {
  stdout: string;
  stderr: string;
  exitCode: string | number;
}

async function runCli(args: string[], cwd: string): Promise<CliResult> {
  let stdout = '';
  let stderr = '';
  const originalCwd = process.cwd();
  const originalExitCode = process.exitCode;
  const stdoutSpy = vi.spyOn(process.stdout, 'write').mockImplementation((chunk: string | Uint8Array) => {
    stdout += chunk.toString();
    return true;
  });
  const consoleLogSpy = vi.spyOn(console, 'log').mockImplementation((...values: unknown[]) => {
    stdout += `${values.map(String).join(' ')}\n`;
  });
  const stderrSpy = vi.spyOn(console, 'error').mockImplementation((...values: unknown[]) => {
    stderr += `${values.map(String).join(' ')}\n`;
  });

  process.exitCode = undefined;
  process.chdir(cwd);
  try {
    const program: Command = createKernelProgram();
    await program.parseAsync(args, { from: 'user' });
    return {
      stdout,
      stderr,
      exitCode: process.exitCode ?? 0
    };
  } finally {
    process.chdir(originalCwd);
    process.exitCode = originalExitCode;
    stdoutSpy.mockRestore();
    consoleLogSpy.mockRestore();
    stderrSpy.mockRestore();
  }
}
