export const GENERATED_FILE_HEADER = '<!-- Generated by Kernel. Edit canonical source under .agent/ instead. -->';
export const MANUAL_START = '<!-- kernel:manual:start -->';
export const MANUAL_END = '<!-- kernel:manual:end -->';

export function withGeneratedHeader(content: string): string {
  if (content.startsWith(GENERATED_FILE_HEADER)) {
    return content;
  }

  return `${GENERATED_FILE_HEADER}\n\n${content}`;
}

export function preserveManualSections(nextContent: string, existingContent: string): string {
  const existingSections = extractManualSections(existingContent);
  if (existingSections.length === 0) {
    return nextContent;
  }

  let sectionIndex = 0;
  let cursor = 0;
  let result = '';

  while (cursor < nextContent.length) {
    const startIndex = nextContent.indexOf(MANUAL_START, cursor);
    if (startIndex === -1) {
      result += nextContent.slice(cursor);
      break;
    }

    const contentStart = startIndex + MANUAL_START.length;
    const endIndex = nextContent.indexOf(MANUAL_END, contentStart);
    if (endIndex === -1) {
      result += nextContent.slice(cursor);
      break;
    }

    result += nextContent.slice(cursor, contentStart);
    result += existingSections[sectionIndex] ?? nextContent.slice(contentStart, endIndex);
    cursor = endIndex;
    sectionIndex += 1;
  }

  return result;
}

function extractManualSections(content: string): string[] {
  const sections: string[] = [];
  let cursor = 0;

  while (cursor < content.length) {
    const startIndex = content.indexOf(MANUAL_START, cursor);
    if (startIndex === -1) {
      break;
    }

    const contentStart = startIndex + MANUAL_START.length;
    const endIndex = content.indexOf(MANUAL_END, contentStart);
    if (endIndex === -1) {
      break;
    }

    sections.push(content.slice(contentStart, endIndex));
    cursor = endIndex + MANUAL_END.length;
  }

  return sections;
}
